[build]
  command = "CI= npm run build"
  publish = "build"
  node_version = "16"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200